name: dashboard
description: Dynamic dashboard widget that allows your users to create their own layouts. Resize, move, indirect resize/move, auto
  re-layout are supported.
version: 0.0.3+1
homepage: https://github.com/Mehmetyaz/dashboard
repository: https://github.com/Mehmetyaz/dashboard

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  haptic_feedback: ^0.5.1+1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
